CREATE DATABASE popular_things;
\c popular_things

CREATE TABLE things (id SERIAL PRIMARY KEY, name TEXT);


 -- ACTIVE RECORD ALLOWS US TO CREATE A SPECIAL CLASS FOR OUR MODELS, HAS
 -- EXACT SAME NAME AS
